'use strict';

module.exports = app => {
 class Controller extends app.Controller {
    async getNav() {
        let { ctx } = this
       let arr=[
       {
           name:"首页",
           children:[]
       },
      {
          name:"商品",
          children:[
              {
                name:"商品首页",
                children:[]
              },
              {
                name:"商品管理",
                children:[
                    {
                        name:"新增商品"
                    },
                    {
                        name:"商品列表"
                    }
                ]
              },
              {
                name:"订单系列",
                children:[
                    {
                        name:"订单列表"
                    },
                    {
                        name:"vip会员"
                    }
                ]
              },
              {
                name:"评价咨询",
                children:[
                    {
                        name:"商品评价"
                    },
                    {
                        name:"商品咨询"
                    }
                ]
              },
          ]
      },
      {
          name:"订单",
          children:[
              {
                name:"订单首页",
                children:[]
              },
              {
                name:"订单管理",
                children:[
                    {
                        name:"订单列表"
                    },
                    {
                        name:"交易结束"
                    },
                    {
                        name:"支付日志"
                    },
                    {
                        name:"退款日志"
                    },
                ]
              },
              {
                name:"售后中心",
                children:[
                    {
                        name:"售后列表"
                    },
                    {
                        name:"商品评价"
                    },
                    {
                        name:"配送轨迹"
                    }
                ]
              },
          ]
      },
      {
          name:"营销",
          children:[
              {
                name:"营销首页",
                children:[]
              },
              {
                name:"营销中心",
                children:[
                    {
                        name:"商品折扣"
                    },
                    {
                        name:"订单促销"
                    }
                ]
              },
              {
                name:"优惠券",
                children:[
                    {
                        name:"优惠券"
                    },
                    {
                        name:"优惠券发放"
                    }
                ]
              },
              {
                name:"购物卡",
                children:[
                    {
                        name:"购物卡"
                    },
                    {
                        name:"购物卡使用"
                    }
                ]
              }
          ]
      },
      {
          name:"会员",
          children:[
              {
                name:"会员首页",
                children:[]
              },
              {
                name:"账号管理",
                children:[
                    {
                        name:"会员账号"
                    },
                    {
                        name:"访问日志"
                    },
                    {
                        name:"账号等级"
                    },
                    {
                        name:"交易结算"
                    }
                ]
              },
              {
                name:"体现审批",
                children:[
                    {
                        name:"提现列表"
                    }
                ]
              },
              {
                name:"咨询问答",
                children:[
                    {
                        name:"问答列表"
                    }
                ]
              },
          ]
      },
      {
          name:"财务",
          children:[
              {
                name:"财务首页",
                children:[]
              },
              {
                name:"快捷向导",
                children:[
                    {
                        name:"交易结算"
                    },
                    {
                        name:"支付日志"
                    },
                    {
                        name:"提现申请"
                    },
                    {
                        name:"退款日志"
                    },
                ]
              }
          ]
      },
      {
          name:"数据",
          children:[
              {
                name:"数据首页",
                children:[]
              },
              {
                name:"统计数据",
                children:[
                    {
                        name:"店铺统计"
                    },
                    {
                        name:"商品统计"
                    },
                    {
                        name:"订单统计"
                    },
                    {
                        name:"会员统计"
                    }
                ]
              }
          ]
      },
      {
          name:"店铺",
          children:[
              {
                name:"系统首页",
                children:[]
              },
              {
                name:"消息管理",
                children:[
                    {
                        name:"我的消息"
                    },
                    {
                        name:"发布消息"
                    }
                ]
              },
              {
                name:"广告发布",
                children:[
                    {
                        name:"广告位置"
                    },
                    {
                        name:"广告列表"
                    }
                ]
              },
              {
                name:"文章发布",
                children:[
                    {
                        name:"新增文章"
                    },
                    {
                        name:"文章管理"
                    },
                    {
                        name:"文章分类"
                    }
                ]
              },
              {
                name:"专题发布",
                children:[
                    {
                        name:"新增专题"
                    },
                    {
                        name:"专题管理"
                    }
                ]
              },
              {
                name:"附件资源",
                children:[
                    {
                        name:"资源管理"
                    },
                    {
                        name:"资源样式"
                    }
                ]
              },
              {
                name:"辅助管理",
                children:[
                    {
                        name:"客服人员"
                    },
                    {
                        name:"配送轨迹"
                    },
                    {
                        name:"友情链接"
                    },
                    {
                        name:"二维码"
                    }
                ]
              },
          ]
      },
      {
          name:"设置",
          children:[
              {
                name:"设置首页",
                children:[]
              },
              {
                name:"运营人员",
                children:[
                    {
                        name:"管理人员"
                    },
                    {
                        name:"操作日志"
                    }
                ]
              },
              {
                name:"权限分配",
                children:[
                    {
                        name:"用户组"
                    },
                    {
                        name:"菜单管理"
                    },
                    {
                        name:"权限规则"
                    }
                ]
              },
              {
                name:"店铺设置",
                children:[
                    {
                        name:"系统管理"
                    },
                    {
                        name:"系统信息"
                    },
                    {
                        name:"前台导航"
                    },
                    {
                        name:"消息模板"
                    }
                ]
              },
              {
                name:"支付系统",
                children:[
                    {
                        name:"支付配置"
                    },
                    {
                        name:"支付日志"
                    }
                ]
              },
              {
                name:"物流管控",
                children:[
                    {
                        name:"区域管理"
                    },
                    {
                        name:"快递公司"
                    },
                    {
                        name:"配送方式"
                    }
                ]
              },
              {
                name:"应用管理",
                children:[
                    {
                        name:"App应用"
                    },
                    {
                        name:"App安装包"
                    },
                    {
                        name:"商业授权"
                    }
                ]
              },
          ]
      },
      {
          name:"云端",
          children:[
              {
                name:"云端首页",
                children:[]
              }
          ]
      },
        ]
        ctx.body = {
            code: 200,
            msg: '获取成功',
            data: arr
        }
    }

 }
 return Controller;
};
